ALTER TABLE produit
ADD COLUMN slug VARCHAR(255),
ADD COLUMN prix_regulier VARCHAR(255),
ADD COLUMN description TEXT,
ADD COLUMN nouveaute BOOLEAN DEFAULT FALSE,
ADD COLUMN vedette BOOLEAN DEFAULT FALSE,
ADD COLUMN offre_speciale BOOLEAN DEFAULT FALSE;
--ADD COLUMN plus_vendu BOOLEAN DEFAULT FALSE;
